### ISSUE TITLE
[Fix] 평균 근무 시간이 이상하게 뜨는 것을 방지하기 위해 calculateAverageTime 함수 조정

### ISSUE THREAD

**Issue by jinwp** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#126]
### 작업할 내용

평균 근무 시간이 1시간 66분 등으로 나오는 현상을 방지하기 위해 CustomCollectionViewCell 의 calculateAverageTime 함수 조정.

### 관련 이슈넘버

#122

**Comment by sunshiningsoo** [comment]
#127 에서 머지
