### ISSUE TITLE
[feat]PlaceInfoView Modal 내에 셀 동적 사이즈 계산 구현

### ISSUE THREAD

**Issue by Willowwryu** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#179]
### 작업할 내용

- 2nd 스프린트에서 생긴 변화로 셀들의 사이즈가 항상 변화하기 때문에 이에 맞춰 동적으로 셀의 크기를 계산하는 기능을 구현

### 관련 이슈넘버

#160

### TODO

- [ ] controllView 내에서 셀 다이나믹 사이즈 구현하기

**Comment by sunshiningsoo** [comment]
#191 일단 보류
