### ISSUE TITLE
[Feat] 캘린더뷰와 리스트뷰 전환 및 리스트뷰 구현

### ISSUE THREAD

**Issue by heokyeol** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#197]
### 작업할 내용

캘린더뷰 이동 버튼을 네비게이션->카드클릭으로 변경
캘린더뷰 진입 후 캘린더, 리스트 전환버튼 구현
리스트 피쳐 구현

- 리스트뷰에 대해 논의 필요
: 헤더 표현 방식, 섹션 구분 단위, 전환 방식

**Comment by sunshiningsoo** [comment]
#198 머지완료
