### ISSUE TITLE
[Bug] 맵 버그 수정

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#199]
### Bug 내용

- [x] 맵에서 자기 자신의 위치를 클릭했을 때 annotation이 눌리는 것, 본인을 나타내는 callOut이 뜨는 것 방지
- [x] 리스트로 보기 버튼 & userTracking 버튼 디자인 수정 -> 사각형으로
- [ ] #200
- [x] 다른 지역 버튼을 눌러서 탐색하다가 placeInfoView, 프로필, 설정 등 다른 뷰로 나갔다가 돌아오면 본인 위치로 map이 reset 되는 것이 불편해 로직 수정하고 반영
- [x] 맵 리스트로 보기 모달을 medium이 아닌 large sheet로 변경
- [x] 나침반 위치 수정

> - [ ] 지역 선택하면 맵 이동 시 어떤 때에는 animation으로 이동하고 또 어떤 때에는 순간이동을 해서 로직 파악하고 수정

일정한 로직이 안 보여서 우선은 이대로 놔두기로

- [ ] #202

### 관련 이슈넘버

#165

### 스크린샷 혹은 gif

- 본인 위치 클릭 시 확대 & callOut 표시
<img src= "https://user-images.githubusercontent.com/103012800/201042228-47c2fabe-2424-4bb7-886a-127db85f1cce.png" width= "300">

- 나침반 위치
<img src= "https://user-images.githubusercontent.com/103012800/201042278-8931bf5d-c95e-45e0-adea-8a1b89c95064.png" width= "300">

- 지역변경 후 다른 뷰 다녀오면 본인 위치로 순간이동 되어있음
<img src= "https://user-images.githubusercontent.com/103012800/201042776-c2bf01d4-1c58-4758-9761-b8ac1c00657f.gif" width= "300">

- 버튼 디자인 사각형으로
<img width="259" alt="image" src="https://user-images.githubusercontent.com/103012800/201043126-9509d285-d4a9-4c75-94be-816c63d6d1fb.png">

**Comment by sunshiningsoo** [comment]
#203 머지완료
