### ISSUE TITLE
[Fix] 캘린더뷰 비짓카드 다중생성 및 코드 리펙토링

### ISSUE THREAD

**Issue by heokyeol** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#205]
### 작업할 내용

기존 한개씩만 나오던 비짓카드를 체크인 갯수에 맞춰 나올 수 있도록 수정함
상기 기능을 위한 리펙토링 진행
체크인하지 않은 날에는 비어있도록 함

**Comment by sunshiningsoo** [comment]
#206 머지완료
