### ISSUE TITLE
[Feat]PlaceInfoView 모달 내부 3번째 셀 ui조정

### ISSUE THREAD

**Issue by Willowwryu** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#208]
### 작업할 내용

- will이 구현한 CheckedProfileListViewCell 의 헤더부분의 ui디자인 차이점 변경 적용

### 스크린샷 혹은 gif

<img width="300" alt="스크린샷 2022-11-11 오후 4 19 21" src="https://user-images.githubusercontent.com/103012086/201287406-7c50844a-f30b-465a-99d2-4f28adff1d3b.png">
<img width="300" alt="스크린샷 2022-11-11 오후 4 19 47" src="https://user-images.githubusercontent.com/103012086/201287471-40d7daa1-9738-4199-bb62-72768466b3df.png">

### TODO

- uistack 뷰 해제후 UIlabel로 텍스트 새로 구현
- 데이터 바인딩 구조 변경 (numbersOfPeaple.count)

**Comment by sunshiningsoo** [comment]
#209  머지완료
