### ISSUE TITLE
논의가 필요한 이슈들🤝

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#24]
# 담당 뷰에서 결정하지 못하는 개발 사항등을 공유해요!

### 하프 모달의 구현방식 차이
- https://github.com/DeveloperAcademy-POSTECH/MacC-Team-NoPower/pull/17#pullrequestreview-1148455850
- 진이 개발중인 워킹스페이스 개수를 보여주는 모달의 방식과 Place Annotation을 클릭했을때 나타나는 모달의 차이가 있어 논의가 필요해 보입니다.
- `워킹스페이스 갯수의 모달`은 2개의 뷰가 동시에 나와 map과 모달을 같이 터치할 수 있는데 반해, `PlaceInfoView`의 경우 뒤에 있는 map의 터치가 안되는 것이 논의사항

-> 1차 개발사항으로 '워킹스페이스 갯수의 모달' 주말동안 더 논의, `PlaceInfoView` apple의 기본 modal 방식

### Team Provisioning Profile
-  Sign In with Apple를 이용해 로그인하는 앱을 팀원들이 각자의 기기로 테스트하며 개발하려면 developer.apple.com에서 App ID 생성, Device UUID & Certification 등록, Profile 생성 등을 하고 각자 Xcode에 등록해야 하는 것 같습니다.

의견 댓글로 달아주시거나 해당 이슈 Edit하셔도 됩니다!
이외의 논의가 필요한 이슈 작성해주세요!✍️

**Comment by limhyoseok** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/59302419/197323956-571e52af-119c-4200-9d4a-db64cab061b0.png">

## 체크인한 사람
- 체크아웃한 사람도 포함 vs 체크아웃한 사람은 제외

## 평균 근무 시간
- 체크아웃하지 않은 사람 포함 vs 체크아웃하지 않한 사람 제외

**Comment by limhyoseok** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/59302419/197324045-fe3db264-9e8e-4c0a-80bd-d449f766d90d.png">

논의할 사항들을 discussion에서 정리하는 것은 어떠신가요?!

**Comment by sunshiningsoo** [comment]
> <img alt="image" width="782" src="https://user-images.githubusercontent.com/59302419/197324045-fe3db264-9e8e-4c0a-80bd-d449f766d90d.png">
> 
> 논의할 사항들을 discussion에서 정리하는 것은 어떠신가요?!

좋습니다.!!

**Comment by sunshiningsoo** [comment]
`Discussion`으로 이관합니다,,
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-NoPower/discussions

**Comment by hardworking-nomad** [comment]
이제 이슈들을 하나씩 별도 디스커션 주제로 올려주시면 될 것 같고 지금까지 나온 건 옮겼습니다.

**Comment by limhyoseok** [comment]
> 이제 이슈들을 하나씩 별도 디스커션 주제로 올려주시면 될 것 같고 지금까지 나온 건 옮겼습니다.

너무 좋습니다!
