### ISSUE TITLE
[Feat] 현재까지 작업된 UI를 모두 병합합니다.

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#31]
### 작업할 내용

- ~~10/21~~ 10/23 18시 까지 작업 완료된 UI들을 병합합니다.
- 바뀐 데이터 구조 적용 https://github.com/DeveloperAcademy-POSTECH/MacC-Team-NoPower/pull/30
- ~~1차로 `PlaceInfoView`는 모달로, `PlaceViewBeforeChekcInView`는 뷰 2개로 진행합니다.~~ -> 맵 터치 가능으로 문제 없어짐

### 관련 이슈넘버

모든 이슈,,,

### TODO

- [x] UI 병합
- [x] UI 업데이트
- [x] 뷰에 필요한 액션 넣기
- [x] 코드 컨벤션 통일

**Comment by sunshiningsoo** [comment]
273aa3419890af1a80569349852ae7076e8263c7 에서 1차 병합

**Comment by hardworking-nomad** [comment]
당장 이번주까지 고칠 것들인지 모르겠지만 눈에 보이는 것들 우선 적습니다!!

- 개인 프로필 내 달력 뷰에서 13월, 14월로 넘어가는 문제 (윤년 로직은 구현은 된 것 같은데, 연도 표시도 해줘야겠네요)
- 주간 통계를 넘겨보거나 월간 달력을 넘겨볼 때 오늘 날짜로 바로 돌아가는 버튼이 필요할 것 같아요.
- 주간 통계 한주씩 넘겨볼 때 날짜 좌우의 chevron 외에 통계 차트 부분 자체도 스와이프 액션 넣으면 편할 듯
- 개인 프로필 내용을 수정하고 확인을 누르면 프로필 뷰에 변경사항 반영 필요
- 지도 클러스터 숫자를 클릭하면 클러스터 어노테이션의 경도 위치를 살짝 보정해서 span으로 확대하는데, 확대된 화면에 아무 핀이 안보일 때가 있어서 span값 조정이 필요해보입니다.
- 하단 모달의 grabber가 아이폰 기본 grabber와 겹치는 문제
