### ISSUE TITLE
[Enhancement] mapView에 들어갈 커스텀버튼 에셋추가

### ISSUE THREAD

**Issue by YeeunKim-archive** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#313]
### 작업할 내용

맵뷰에서 핀 보기 방식 선택하는 버튼을 위한 에셋 이미지를 추가합니다. 

### 스크린샷 혹은 gif

<img width="300" alt="스크린샷 2022-11-24 오후 2 47 22" src="https://user-images.githubusercontent.com/95920991/203703891-2e917365-5fca-4739-8336-23397cf2f8ed.png">

**Comment by sunshiningsoo** [comment]
#315 에서 머지완료
