### ISSUE TITLE
[Bug] 장소핀 연달아 터치 시 annotation 터치 해제가 안되어 버튼이 diabled 되는 현상 해결

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#338]
### Bug 내용

장소핀 두개 연달아 클릭하면 첫 번째 annotation 터치 해제 처리가 되지 않아 다른 버튼들(프로필, 설정 등 맵뷰의 모튼 버튼들)이 gray 색상으로 변한 채 원복되지 않는 버그

### 스크린샷 혹은 gif

<img src="https://user-images.githubusercontent.com/103012800/204220168-c277308e-a234-4056-a381-8386eb2a708b.png" width="300">

**Comment by sunshiningsoo** [comment]
close #339
