### ISSUE TITLE
[Feat] 캘린더뷰, 리스트뷰의 순서 변경 및 버그픽스

### ISSUE THREAD

**Issue by heokyeol** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#349]
### 작업할 내용

캘린더뷰와 리스트뷰의 순서를 변경합니다
프로필뷰 이외 비짓카드에서 체크아웃하지 않은 경우 데이터 표기방식을 수정합니다
헤더 묶음 방식을 수정합니다
리펙터링을 진행합니다

**Comment by sunshiningsoo** [comment]
기간 너무 길어져 close
