### ISSUE TITLE
[Enhancement] SettingView 필요없는 코드 삭제와 함수 분리를 합니다.

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#356]
### 작업할 내용

`func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {`
위의 delegate 함수가 있는 부분을 이해하기 좋게 바꿉니다..

### Diffable Datasource
 Datasource를 프로토콜의 함수들을 이용하는 방식에서 DiffableDatasource로 바꿀까 고민입니다.. 조금 더 고민해보겠습니다.
 DiffableDatasource를 사용했을때의 장점은, table에 있는 데이터가 없어지거나 추가될때의 자연스러운 애니메이션의 전환인데,

우리앱의 경우 row가 로그아웃, 로그인의 경우에서만 변화하는데, 이런 설정탭의 특성상 바꾸는게 좋은 선택인지는 더 고민해보도록 하겠습니다.
[Diffable datasource의 자연스러운 애니메이션](https://velog.io/@ellyheetov/UI-Diffable-Data-Source)

### Diffable DataSource 사용안하기로 결정
 Diffable DataSource를 사용할 경우의 장점은 데이터의 변화가 많을때라고 생각하는데, 설정뷰의 테이블의 경우 이에 해당하지 않는다고 생각해서 사용하지 않았습니다

<img width="628" alt="스크린샷 2023-01-05 22 26 03" src="https://user-images.githubusercontent.com/72736657/210790456-afdf4c9b-1944-4f0d-adbb-18624f88b206.png">

과거의 나 반성해라

**Comment by eunbkang** [comment]
멋있습니다
