### ISSUE TITLE
[Feat] 데이터 구조를 변경합니다

### ISSUE THREAD

**Issue by limhyoseok** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#4]
### 작업할 내용

# 변경이유
- 파이어 베이스 쿼리를 고려
- 통계 데이터 고려
- 놓친 부분 채우기

# 기존 데이터 구조
<img width="606" alt="image" src="https://user-images.githubusercontent.com/59302419/196312945-cd3a6676-7d5c-4106-a6af-deb0f056764c.png">

**Comment by sunshiningsoo** [comment]
#30 에서 머지 완료!
