### ISSUE TITLE
[Feat] 체크인된 날자 도장찍기 / 선택한 날 카드 보여주기

### ISSUE THREAD

**Issue by heokyeol** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#43]
### 작업할 내용

프로필 하위의 캘린더뷰 feature을 완성하는 단계입니다
체크인 기록이 존재하는 날에 도장을 찍습니다
선택한 날에 해당하는 체크인 데이터 카드를 보여줍니다
체크인 카드는 딜리게이트를 사용할 예정입니다

**Comment by sunshiningsoo** [comment]
#50 에서 머지완료
