### ISSUE TITLE
[Feat] PlaceInfoview Modal  UI Design 변경에 따른 컴포넌트 수정

### ISSUE THREAD

**Issue by Willowwryu** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#51]
### 작업할 내용

- 뷰 디자인 변경에 따른 컴포넌트 수정

### 관련 이슈넘버

#12, #28

### 스크린샷 혹은 gif

<img width="208" alt="스크린샷 2022-10-24 오후 10 59 58" src="https://user-images.githubusercontent.com/103012086/197543996-e44627df-c167-48a4-84f2-76036c68b5fb.png">

### TODO

- [x] 기존 컴포넌트 위치수정
- [x] 삭제 될 컴포넌트 정하기
- [x] 새 컴포넌트 구현

**Comment by sunshiningsoo** [comment]
기존 UI가 더 좋은 것 같다는 생각으로 PR close
