### ISSUE TITLE
[Feat] 해야할 작업 리스트

### ISSUE THREAD

**Issue by limhyoseok** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#84]
### 작업할 내용
- [x] #91
- [x] #87
- [x] #86
- [x] #85
- [x] #96
  - [x] 체크아웃 구현 
  - [x] #119
- [x] #93

- [x] #97
- [x] 체크인 유지가 되지 않음 - 성수 #88 

- [x] 체크인 하면 다른 장소 체크인 비활성화 - 성수

- [x] #89
- [x] 프로필 수정 파이어베이스에 반영 - 결
- [x] #98  - 윌로우
- [x] #108

- [x] 어노테이션에서 바로 접근하면 체크인 후에 디스미스됨 - 히로
- [x] #106
- [x] 네비게이션 lifecycle 버그 수정 - 결
- [x] #114
- [x] #105
- [x] #109
- [x] #107

**Comment by sunshiningsoo** [comment]
1차 TestFlight 완료! 10/28
