### ISSUE TITLE
체크인 상태에서 앱 종료 후 다시 실행시 체크인 한 장소를 중심으로 하프모달 뷰 보도록 하기

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#97]
ToDo
- [ ] 앱 실행 시 Login 확인, CheckIn 여부 확인
- [ ] 체크인 상태일 때 체크인 장소로 MapRegion 이동 (해당 place의 좌표와 적정 span 값 전달)
- [ ] 하프모달 하단에 띄우기

**Comment by sunshiningsoo** [comment]
#141 에서 머지완료
